[package]
name = "scratch-test-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.13.0"
dotenvy = "0.15.7"
env_logger = "0.11.9"
log = "0.4.32"
schemars = "1.2.1"
serde = "1.0"
serde_json = "1.0"
utoipa = { version = "5.5.0", default-features = false, features = ["macros", "actix_extras"] }
utoipa-actix-web = { version = "0.1.2" }
utoipa-scalar = { version = "0.3.0", default-features = false, features = ["actix-web"] }

[dependencies.skoin2627]
git = "https://github.com/Marcel-Scherzinger/scratch-test-koin2627"
package = "scratch-test-koin2627"
features = ["serde"]

[dependencies.sreport]
git = "https://github.com/Marcel-Scherzinger/scratch-test-report"
package = "scratch-test-report"
features = ["serde", "schemars", "utoipa"]

[dependencies.svalue]
git = "https://github.com/Marcel-Scherzinger/scratch-test-value"
package = "scratch-test-value"
default-features = false
features = ["serde", "schemars", "utoipa", "thread-share"]

[dependencies.smodel]
git = "https://github.com/Marcel-Scherzinger/scratch-test-model"
package = "scratch-test-model"
default-features = false
features = ["sb3", "serde", "schemars"]

